routes/user.py
from flask import Blueprint, request, redirect, url_for, flash, render_template,jsonify, session
from dotenv import load_dotenv
import os
from flask_login import login_required, current_user
from models import carts_collection,menus_collection,orders_collection,get_cart_details, get_shipment
from bson import ObjectId
from midtransclient import Snap
import uuid
import datetime
import pytz

user_bp = Blueprint('user', __name__)
load_dotenv()

midtrans_client = Snap(
    is_production=False,
    server_key=(os.getenv('MIDTRANS_SERVER_KEY')),
    client_key=(os.getenv('MIDTRANS_CLIENT_KEY'))
)


@user_bp.route('/add_to_cart/<menu_id>', methods=['POST'])
@login_required
def add_to_cart(menu_id):
    
    quantity = int(request.form.get('quantity', 1))
    query = {
        'user_id': ObjectId(current_user.id)
    }
    user_cart = carts_collection.find_one(query)

    if user_cart:
        updated = False
        for item in user_cart['cart_items']:
            if item['menu_id'] == ObjectId(menu_id):
                item['quantity'] += quantity
                updated = True
                break
        
        if not updated:
            new_item = {
                'menu_id': ObjectId(menu_id),
                'quantity': quantity
            }
            user_cart['cart_items'].append(new_item)

        carts_collection.update_one(query, {'$set': {'cart_items': user_cart['cart_items']}})
        flash('Menu Berhasil Ditambahkan','success')
    else:
        
        cart_item = {
            'user_id':ObjectId(current_user.id),
            'cart_items': [{
                'menu_id':  ObjectId(menu_id),
                'quantity': quantity
            }]
        }
        carts_collection.insert_one(cart_item)
        flash('Menu Berhasil Ditambahkan','success')

    # Redirect to the previous page or the cart page
    return redirect(url_for("index"))

@user_bp.route('/keranjang')
@login_required
def keranjang():
    cart_items_count = get_cart_items_count()
    cart_details = get_cart_details()

    return render_template('user/keranjang.html', cart_items_count=cart_items_count, cart_details=cart_details)

@user_bp.route('/menu')
@login_required
def menu():
    cart_items_count = get_cart_items_count()
    menus = list(menus_collection.find({}))
    categories = menus_collection.distinct('kategori')
    return render_template('user/menu.html', menus=menus, categories=categories, cart_items_count=cart_items_count)
    
@user_bp.route('/update_quantity/<menu_id>', methods=['POST'])
@login_required
def update_quantity(menu_id):
    action = request.form.get('action')
    quantity = int(request.form.get('quantity', 1))
    query = {
        'user_id': ObjectId(current_user.id)
    }
    user_cart = carts_collection.find_one(query)

    if user_cart:
        for item in user_cart['cart_items']:
            if item['menu_id'] == ObjectId(menu_id):
                if action == 'increase':
                    item['quantity'] += 1
                elif action == 'decrease' and item['quantity'] > 1:
                    item['quantity'] -= 1
                break

        carts_collection.update_one(query, {'$set': {'cart_items': user_cart['cart_items']}})
    return redirect(url_for('user.keranjang'))

@user_bp.route('/delete_menu/<menu_id>', methods=['POST'])
@login_required
def delete_menu(menu_id):
    query = {'user_id': ObjectId(current_user.id)}
    update = {'$pull': {'cart_items': {'menu_id': ObjectId(menu_id)}}}
    result = carts_collection.update_one(query, update)

    result.modified_count > 0
    
    return redirect(url_for('user.keranjang'))


@user_bp.route('/checkout', methods=['POST'])
@login_required
def checkout():
    timezone = pytz.timezone('Asia/Jakarta')
    current_datetime = datetime.datetime.now(timezone)
    expiry_time = current_datetime + datetime.timedelta(days=1)
    expiry_time_str = expiry_time.strftime('%Y-%m-%d %H:%M:%S %z')
    delivery_date = request.form.get('deliveryDate')
    delivery_address = {
        'province': request.form.get('province'),
        'district': request.form.get('district'),
        'sub_district': request.form.get('subDistrict'),
        'village': request.form.get('village'),
        'zipcode': request.form.get('zipcode'),
        'street_address': request.form.get('streetAddress')
    }
    if current_user.is_authenticated:
        user_id = ObjectId(current_user.id)
        cart_details = get_cart_details()
    
        if cart_details:
            items_details = []
            item_details = [
                            {
                                "id": item['menu_id'],
                                "price": item['harga'],
                                "quantity": item['quantity'],
                                "name": item['nama'],
                                "category": item['kategori']
                            }
                            for item in cart_details['cart_items']
                        ]
            for item in cart_details['cart_items']:
                item_detail = {
                    'id': ObjectId(item['menu_id']),  # Sesuaikan dengan field yang sesuai dari MongoDB
                    # 'price': item['harga'],  # Harga per item
                    'quantity': item['quantity'],  # Jumlah item
                    # 'name': item['nama'],  # Nama item
                    # 'category': item['kategori']  # Kategori item (opsional)
                }
                items_details.append(item_detail)

            # Prepare customer details
            customer_details = {
                'first_name': cart_details['user']['name'],
                'email': cart_details['user']['email'],
                'phone': cart_details['user']['phone'],
                "billing_address": {
                    "first_name": cart_details['user']['name'],
                    "email": cart_details['user']['email'],
                    "phone": cart_details['user']['phone'],
                },
                "shipping_address": {
                    "first_name": cart_details['user']['name'],
                    "email": cart_details['user']['email'],
                    "phone": cart_details['user']['phone'],
                    "address": f'{delivery_address["street_address"]}, {delivery_address["village"]},',
                    "city": f'{delivery_address["sub_district"]}, {delivery_address["district"]}, {delivery_address["province"]}',
                    "postal_code": delivery_address['zipcode'],
                    "country_code": "IDN"
                }
            }

            # Create transaction token using Snap API
            transaction_details = {
                'transaction_details': {
                    'order_id': f'LanggengCatering-{uuid.uuid4().hex[:4]}',
                    'gross_amount': cart_details['grandTotalWithPPN']
                },
                
                "item_details": item_details,
                'customer_details': customer_details,
                'credit_card': {
                    'secure': True
                },
                "callbacks": {
                    "finish": "{{url_for('user.order')}}",
                    "error": "https://your-domain.com/midtrans/error"
                }
            }

            try:
                # Create Snap token
                snap_token = midtrans_client.create_transaction(transaction_details)['token']
                
                # Save order details to orders_collection
                order_data = {
                    'user_id': ObjectId(user_id),
                    'order_id': transaction_details['transaction_details']['order_id'],
                    'order_date': current_datetime.strftime('%Y-%m-%d %H:%M:%S %z'),
                    'expiry_time':expiry_time_str,
                    'delivery_date': delivery_date,
                    'total_amount': int(cart_details['grandTotal']),
                    'payment_status': 'pending',
                    'snap_token': snap_token,
                    "item_details": items_details,  # Save cart items to order
                    'delivery_address': delivery_address,
                }
                orders_collection.insert_one(order_data)

                # Clear the user's cart
                carts_collection.delete_one({'user_id': user_id})

                return jsonify({'snap_token': snap_token}), 200

            except Exception as e:
                print(f"Error: {str(e)}")
                return jsonify({'error': 'Failed to initiate payment'}), 500

    return jsonify({'error': 'Cart not found'}), 404


@user_bp.route('/midtrans_webhook', methods=['POST'])
def midtrans_webhook():
    webhook_data = request.get_json()

    # Log the received webhook dat
    # Process data from webhook Midtrans
    order_id = webhook_data.get('order_id')
    transaction_time = webhook_data.get('transaction_time')
    gross_amount = webhook_data.get('gross_amount')
    transaction_status = webhook_data.get('transaction_status')
    expiry_time = webhook_data.get('expiry_time')


    # Prepare data to be saved
    order_data = {
        'order_id': order_id,
        'order_date': transaction_time,
        'expiry_time' : expiry_time,
        'payment_status': transaction_status,
        
    }
    if expiry_time:
        order_data['expiry_time'] = expiry_time

    orders_collection.update_one(
        {"order_id": order_id},
        {"$set": order_data},
        upsert=True
    )

    return jsonify({"message": "Webhook received"}), 200


@user_bp.route('/orders', methods=['GET'])
@login_required
def get_order():
    user_id = ObjectId(current_user.id)  # Sesuaikan dengan cara Anda mendapatkan user ID
    orders = get_shipment()
    cart_items_count = get_cart_items_count()
    return render_template('user/pesanan.html', orders=orders, cart_items_count=cart_items_count,)


def get_cart_items_count():
    if current_user.is_authenticated:
        user_id = ObjectId(current_user.id)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Deskripsi singkat tentang halaman web Anda.">
    <meta name="keywords" content="kata kunci, yang, relevan, dengan, halaman, Anda">
    <meta name="author" content="Nama Anda atau Nama Perusahaan Anda">
    <title>{% block title %}{% endblock %} | Langgeng Catering</title>
    <!-- Menambahkan link untuk favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='assets/img/logo.png') }}" type="image/png">
    <!-- Menambahkan link untuk stylesheet lokal -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    
</head>

<body>
    {% if navbar %}
    <!-- Navbar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary shadow rounded-bottom-5 p-3 sticky-top">
        <div class="container">
            <a class="navbar-brand text-primary fs-5 fw-bold mx-2 d-none d-md-block" href="{{url_for('index')}}">Langgeng<span
                    class="text-secondary">Catering</span></a>
            <ul class="navbar-nav justify-content-center d-none d-lg-flex mb-2 mb-lg-0 nav-underline">
                <li class="nav-item mx-4">
                    <a class="nav-link {% if request.path == url_for('index') %} fw-bold text-primary active{% endif %}"
                        href="{{ url_for('index') }}">Home</a>
                </li>
                <li class="nav-item mx-4">
                    <a class="nav-link {% if request.path == url_for('user.menu') %} fw-bold text-primary active{% endif %}"
                    href="{{ url_for('user.menu') }}">Menu</a>
                </li>
                <li class="nav-item mx-4">
                    <a class="nav-link " href="">Galeri</a>
                </li>
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
            {% if current_user.is_authenticated %}
            <div class="d-flex  text-primary justify-content-end mx-2">
                <div class="d-flex ">
                    <a class="nav-link ms-2 position-relative my-3 text-center" href="{{url_for('user.keranjang')}}">
                        <ion-icon name="bag-outline" class="text-primary fs-3"></ion-icon>
                        {% if cart_items_count > 0 %}
                        <span id="cartItemCount"
                            class="position-absolute top-20 start-100 translate-middle badge rounded-pill bg-danger">{{ cart_items_count }}
                            <span class="visually-hidden">unread messages</span>
                        </span>
                        {% endif %}
                    </a>
                </div>

                <div class="dropdown ms-2 d-none d-lg-flex">
                    <button class="btn" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img  src="https://avatar.iran.liara.run/public" alt="" width="30">
                    </button>
                    <ul class="dropdown-menu rounded-3 me-5 shadow w-100" data-bs-theme="light">
                        <li><a class="dropdown-item rounded-2 text-decoration-none" href=""><ion-icon name="person-outline"></ion-icon></i> Akun
                                Saya</a></li>
                        <li><a class="dropdown-item rounded-2 text-decoration-none" href="{{url_for('user.get_order')}}"><ion-icon name="receipt-outline"></ion-icon></i> Pesanan</a></li>
                        <li>
                            <hr class="dropdown-divider">
                            </hr>
                        <li><a class="dropdown-item rounded-2" href="{{url_for('logout')}}"><ion-icon name="log-out-outline"></ion-icon> Keluar</a></li>
                    </ul>
                </div>

            </div>
            {% else %}
            <div class="mx-2 d-none d-lg-flex">
                <a class="text-decoration-none" href="{{ url_for('auth.login') }}">
                    <button type="button" class="btn btn-outline-primary rounded-3 mx-3">
                        Masuk
                    </button>
                </a>
                <a class="text-decoration-none" href="{{ url_for('auth.register') }}">
                    <button type="button" class="btn btn-primary rounded-3">
                        Daftar
                    </button>
                </a>
            </div>
            {%endif%}
        </div>
    </nav>
    <!-- Nav Bottom -->
    <nav
        class=" rounded-top-5 shadow navbar navbar-expand-lg navbar-light d-block bg-light fixed-bottom justify-content-around d-lg-none d-md-block">
        <div class="container-fluid">
            <div class="container">
                <div class="row">
                    <a class="nav-link col text-center p-2 p-md-3 {% if request.path == url_for('index') %}active fw-bold text-white bg-primary rounded-4 {% endif %}"
                        href="{{ url_for('index') }}"><ion-icon name="home-outline" class="fs-3"></ion-icon></a>
                    <a class="nav-link col text-center p-2 p-md-3 {% if request.path == url_for('user.menu') %}active fw-bold text-white bg-primary rounded-4 {% endif %}"
                    href="{{ url_for('user.menu') }}"
                        href=""><ion-icon name="fast-food-outline" class="fs-3"></ion-icon></a>
                    <a class="nav-link col text-center p-2 p-md-3 {% if request.path == url_for('user.get_order') %}active fw-bold text-white bg-primary rounded-4 {% endif %}" href="{{ url_for('user.get_order') }}"><ion-icon name="receipt-outline" class="fs-3"></ion-icon></a>
                    <a class="nav-link col text-center p-2 p-md-3{% if request.path == url_for('user.get_order') %}active fw-bold text-white bg-primary rounded-4 {% endif %}" href="{{ url_for('user.get_order') }}" ><ion-icon name="person-outline" class="fs-3"></ion-icon></i></a>
                </div>

            </div>
        </div>
    </nav>
    <!-- End -->
    {% endif %}


    {% block content %}{% endblock %}


    <!-- Menambahkan script untuk Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
        crossorigin="anonymous"></script>
    
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% block title %}
Home
{% endblock %}
{% set navbar = True %}
{% block content %}
<!-- Hero -->
<section>
    <div class="container my-4">
        <div class="card rounded-5 overflow-hidden">
            <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    <div class="carousel-item ratio ratio-21x9 active" data-bs-interval="10000">
                        <img src="https://images.unsplash.com/photo-1529566652340-2c41a1eb6d93?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                            class="d-block img-fluid   object-fit-cover " alt="...">
                    </div>
                    <div class="carousel-item ratio ratio-21x9" data-bs-interval="2000">
                        <img src="https://images.unsplash.com/photo-1695712468478-789ccc733903?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
                            class="d-block img-fluid object-fit-cover" alt="...">
                    </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval"
                    data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval"
                    data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>
    </div>
</section>

<!-- List Kategori Menu -->
<section class="py-3">
    <div class="container px-2 px-lg-3">
        <div class="row my-2">
            <div class="col-12 col-md-10 col-lg-8 col-xl-7">
                <h2 class="fs-4">Kategori Menu</h2>
            </div>
        </div>
    </div>

    <div class="container overflow-hidden px-2">
        <div class="row g-2">
            <div class="col-6 col-sm-3 my-2">
                <div class="card shadow-sm bg-white rounded-3">
                    <div class="card-body text-center p-1">
                        <img src="{{url_for('static',filename='assets/img/svg/lunch-box.svg')}}" class=" img-fluid"
                            alt="" width="30%" height="30%">
                        <a href="#" class="stretched-link mt-1 fs-6 text-decoration-none d-flex justify-content-center">
                            <h5 class="text-dark mb-0">Nasi Kotak</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-6 col-sm-3 my-2">
                <div class="card shadow-sm bg-white rounded-3">
                    <div class="card-body text-center p-1">
                        <img src="{{url_for('static',filename='assets/img/svg/fruit.svg')}}" alt="" class="img-fluid"
                            width="30%" height="30%">
                        <a href="#" class="stretched-link mt-1 fs-6 text-decoration-none d-flex justify-content-center">
                            <h5 class="text-dark mb-0">Snack Box</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-6 col-sm-3 my-2">
                <div class="card shadow-sm bg-white rounded-3">
                    <div class="card-body text-center p-1">
                        <img src="{{url_for('static',filename='assets/img/svg/catering.svg')}}" alt="" class="img-fluid"
                            width="30%" height="30%">
                        <a href="#" class="stretched-link mt-1 fs-6 text-decoration-none d-flex justify-content-center">
                            <h5 class="text-dark mb-0">Prasmanan</h5>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-6 col-sm-3 my-2">
                <div class="card shadow-sm bg-white rounded-3">
                    <div class="card-body text-center p-1">
                        <img src="{{url_for('static',filename='assets/img/svg/tumpeng.svg')}}" alt="" class="img-fluid"
                            width="30%" height="30%">
                        <a href="#" class="stretched-link mt-1 fs-6 text-decoration-none d-flex justify-content-center">
                            <h5 class="text-dark mb-0">Tumpeng</h5>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- Produk Andalan -->
<section class="py-5">
    <div class="container px-4 px-lg-5">
        <div class="row">
            <div class="col-md-4">
                <h1>Produk Kami</h1>
            </div>
            <div class="col-md-8 justify-content-between d-flex">
                <ul class="nav nav-pills ms-auto" id="pills-tab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <button class="nav-link active rounded-5  p-2 px-4 me-2 my-2 border border-primary"
                            id="pills-semuaMenu-tab" data-bs-toggle="pill" data-bs-target="#pills-semuaMenu"
                            type="button" role="tab" aria-controls="pills-semuaMenu" aria-selected="true">Semua
                            Menu</button>
                    </li>
                    {% for category in categories %}
                    <li class="nav-item" role="presentation">
                        <button class="nav-link rounded-5  p-2 px-4 me-2 my-2 border border-primary"
                            id="pills-{{ category|lower|replace(' ', '') }}-tab" data-bs-toggle="pill"
                            data-bs-target="#pills-{{ category|lower|replace(' ', '') }}">{{ category }}</button>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="tab-content my-4" id="pills-tabContent">
            <div class="tab-pane fade show active" id="pills-semuaMenu" role="tabpanel"
                aria-labelledby="pills-semuaMenu-tab" tabindex="0">
                <div class="row ">
                    {% for menu in menus %}
                    <div class="col-6 col-md-4 col-lg-3 my-3">
                        <div class="rounded position-relative">
                            <div class="ratio ratio-4x3">
                                <img class="img-fluid object-fit-cover rounded-top"
                                    src="{{ url_for('static', filename=menu.gambar[7:]) }}" alt="{{menu.nama}}">
                            </div>
                            <div class="text-white bg-secondary px-3 py-1 rounded position-absolute"
                                style="top: 10px; left: 10px;">{{menu.kategori}}</div>
                            <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                                <h4 class="fw-bold">{{menu.nama}}</h4>
                                <p>Minimal Pembelian {{menu.minimal_pembelian}}</p>
                                <div
                                    class="justify-content-between d-block justify-content-center align-items-center">
                                    <strong>{{ menu.harga | format_idr }}</strong>
                                    <form method="POST" action="{{ url_for('user.add_to_cart', menu_id=menu._id) }}">
                                        <input type="hidden" name="menu_id" value="{{ menu._id }}">
                                        <button type="submit"
                                            class="btn border border-secondary rounded-pill px-3 btn-secondary mt-3">
                                            <ion-icon name="bag-add-outline"></ion-icon>
                                            Keranjang
                                        </button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            {% for category in categories %}
            <div class="tab-pane fade" id="pills-{{ category|lower|replace(' ', '') }}" role="tabpanel"
                aria-labelledby="pills-{{ category|lower|replace(' ', '') }}-tab">
                <div class="row">
                    {% for menu in menus %}
                    {% if menu.kategori == category %}
                    <div class="col-6 col-md-4 col-lg-3 my-3">
                        <div class="rounded position-relative">
                            <div class="ratio ratio-4x3">
                                <img class="img-fluid object-fit-cover rounded-top"
                                    src="{{ url_for('static', filename=menu.gambar[7:]) }}" alt="{{menu.nama}}">
                            </div>
                            <div class="text-white bg-secondary px-3 py-1 rounded position-absolute"
                                style="top: 10px; left: 10px;">{{menu.kategori}}</div>
                            <div class="p-4 border border-secondary border-top-0 rounded-bottom">
                                <h4 class="fw-bold">{{menu.nama}}</h4>
                                <p>Minimal Pembelian {{menu.minimal_pembelian}}</p>
                                <div
                                    class="justify-content-between d-block justify-content-center align-items-center">
                                    <strong>{{ menu.harga | format_idr }}</strong>
                                    <form method="POST" action="{{ url_for('user.add_to_cart', menu_id=menu._id) }}">
                                        <input type="hidden" name="menu_id" value="{{ menu._id }}">
                                        <button type="submit"
                                            class="btn border border-secondary rounded-pill px-3 btn-secondary mt-3">
                                            <ion-icon name="bag-add-outline"></ion-icon>
                                            Keranjang
                                        </button>
                                    </form>

                                </div>
                            </div>
                        </div>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="row">
            <div class="justify-content-center text-center">
                <a href="" class="text-decoration-none text-secondary fw-bold fs-5">Lihat Semua Menu</a>
            </div>
        </div>
    </div>
</section>
<!-- End Produk Andalan -->

{% endblock %}